function titleCase(value) {
  if (!value) {
    return 'Unknown'
  }
  return `${value}`.charAt(0).toUpperCase() + `${value}`.slice(1)
}

const CJK_TEXT_PATTERN = /[\u3400-\u9fff\uf900-\ufaff]/

export function formatLocation(filePath, line) {
  return line ? `${filePath}:${line}` : filePath
}

export function displayEnglishOrFallback(value, fallback) {
  const text = `${value || ''}`.trim()
  if (!text || CJK_TEXT_PATTERN.test(text)) {
    return fallback
  }
  return text
}

function evidenceLines(finding) {
  return Array.isArray(finding?.evidence_lines)
    ? finding.evidence_lines.filter(Boolean)
    : []
}

function evidenceBlockForFinding(finding) {
  const lines = evidenceLines(finding)
  if (!lines.length) {
    return 'No validated diff line was found for this note. Manual confirmation is required.'
  }

  return ['```diff', ...lines, '```'].join('\n')
}

function evidenceBlockForGroup(group) {
  const lines = ['```diff']
  let hasEvidence = false

  for (const item of group.items) {
    const itemLines = evidenceLines(item.original)
    if (!itemLines.length) {
      continue
    }
    hasEvidence = true
    lines.push(`# ${formatLocation(item.file_path, item.line)}`)
    lines.push(...itemLines)
    lines.push('')
  }

  if (!hasEvidence) {
    return 'No validated diff line was found for this note. Manual confirmation is required.'
  }

  lines.push('```')
  return lines.join('\n').replace(/\n```$/, '```')
}

export function findingDisplayTitle(finding) {
  return displayEnglishOrFallback(
    finding?.comment_title || finding?.github_comment_title || finding?.title,
    `Review issue in ${formatLocation(finding?.file_path || 'changed file', finding?.line)}`,
  )
}

export function findingDisplaySummary(finding) {
  return displayEnglishOrFallback(
    finding?.comment_summary ||
      finding?.github_comment_summary ||
      finding?.summary,
    'AI review identified a potential issue at this location. Please verify the evidence and Diff before posting or applying a change.',
  )
}

export function findingDisplaySuggestion(finding) {
  return displayEnglishOrFallback(
    finding?.comment_suggestion ||
      finding?.github_comment_suggestion ||
      finding?.suggestion,
    'Review the affected change manually and update the implementation, documentation, or tests if the risk is confirmed.',
  )
}

function groupDisplayTitle(group) {
  const firstFinding = group.items[0]?.original
  return displayEnglishOrFallback(
    group.commentTitle || firstFinding?.comment_title || group.title,
    `Review issue affecting ${group.items.length} location${group.items.length > 1 ? 's' : ''}`,
  )
}

function groupDisplaySummary(group) {
  const firstFinding = group.items[0]?.original
  return displayEnglishOrFallback(
    group.commentSummary || firstFinding?.comment_summary || group.description,
    'AI review identified a potential issue across the affected locations. Please verify the evidence and Diff before posting or applying a change.',
  )
}

function groupDisplaySuggestion(group) {
  const firstFinding = group.items[0]?.original
  return displayEnglishOrFallback(
    group.commentSuggestion ||
      firstFinding?.comment_suggestion ||
      group.suggestion,
    'Review every affected location manually and update the implementation, documentation, or tests if the risk is confirmed.',
  )
}

export function findingGroupDisplayTitle(group) {
  return groupDisplayTitle(group)
}

export function findingGroupDisplaySummary(group) {
  return groupDisplaySummary(group)
}

export function findingGroupDisplaySuggestion(group) {
  return groupDisplaySuggestion(group)
}

export function formatFindingAsGithubComment(finding) {
  const location = formatLocation(finding.file_path, finding.line)

  return [
    '**AI Review Suggestion**',
    '',
    `**Severity**: ${titleCase(finding.severity)}`,
    '',
    `**Issue**: ${findingDisplayTitle(finding)}`,
    '',
    `**Location**: \`${location}\``,
    '',
    '**Details**:',
    findingDisplaySummary(finding),
    '',
    '**Evidence**:',
    evidenceBlockForFinding(finding),
    '',
    '**Suggestion**:',
    findingDisplaySuggestion(finding),
    '',
    'Generated by AI PR Review Assistant for reference only. Please verify manually before applying.',
  ].join('\n')
}

export function formatFindingGroupAsGithubComment(group) {
  const locations = group.items
    .map((item) => `- \`${formatLocation(item.file_path, item.line)}\``)
    .join('\n')
  const locationLabel =
    group.items.length === 1 ? '**Affected location**:' : '**Affected locations**:'

  return [
    '**AI Review Suggestion**',
    '',
    `**Severity**: ${titleCase(group.severity)}`,
    '',
    `**Issue**: ${groupDisplayTitle(group)}`,
    '',
    locationLabel,
    locations,
    '',
    '**Details**:',
    groupDisplaySummary(group),
    '',
    '**Evidence**:',
    evidenceBlockForGroup(group),
    '',
    '**Suggestion**:',
    groupDisplaySuggestion(group),
    '',
    'Generated by AI PR Review Assistant for reference only. Please verify manually before applying.',
  ].join('\n')
}

export function formatPendingFindingAsGithubComment(finding, reviewSource) {
  const evidence = evidenceLines(finding).length
    ? evidenceBlockForFinding(finding)
    : 'No validated diff line was found for this pending note. Manual confirmation is required.'
  const fallbackNote =
    reviewSource === 'local_fallback' || reviewSource === 'fallback'
      ? [
          '',
          '> This note comes from local fallback heuristics and does not mean an LLM review was successfully completed.',
        ]
      : []

  return [
    '**AI Pending Review Note**',
    '',
    `**Pending Issue**: ${findingDisplayTitle(finding)}`,
    '',
    `**Potentially related file**: \`${finding.file_path || 'unknown file'}\``,
    '',
    '**Details**:',
    displayEnglishOrFallback(
      finding.comment_summary || finding.github_comment_summary || finding.summary,
      'The model raised this issue, but the current evidence or context is insufficient, so it is not treated as a confirmed risk.',
    ),
    '',
    '**Evidence Status**:',
    evidence,
    '',
    '**Manual Confirmation Suggested**:',
    findingDisplaySuggestion(finding),
    '',
    '> Generated by AI PR Review Assistant. This note is pending confirmation and does not represent a validated risk.',
    ...fallbackNote,
  ].join('\n')
}

export async function copyTextToClipboard(text) {
  if (navigator.clipboard?.writeText) {
    await navigator.clipboard.writeText(text)
    return
  }

  const textarea = document.createElement('textarea')
  textarea.value = text
  textarea.setAttribute('readonly', '')
  textarea.style.position = 'fixed'
  textarea.style.left = '-9999px'
  document.body.appendChild(textarea)
  textarea.select()
  document.execCommand('copy')
  document.body.removeChild(textarea)
}

export function groupFindings(findings) {
  const groups = new Map()

  for (const finding of findings) {
    const category = finding.category || ''
    const groupKey = `${finding.severity || ''}::${category}::${finding.title || ''}`
    const item = {
      file_path: finding.file_path,
      line: finding.line,
      evidence: evidenceLines(finding).join('\n'),
      original: finding,
    }

    if (!groups.has(groupKey)) {
      groups.set(groupKey, {
        groupKey,
        title: finding.title,
        severity: finding.severity,
        category,
        description: finding.summary,
        suggestion: finding.suggestion,
        evidence: item.evidence,
        commentTitle: finding.comment_title,
        commentSummary: finding.comment_summary,
        commentSuggestion: finding.comment_suggestion,
        items: [item],
      })
      continue
    }

    groups.get(groupKey).items.push(item)
  }

  return Array.from(groups.values())
}
